export const routes = {
  WORK_PLACE: '/work-place',
  REFUSES: '/work-place/refuses',
  RETURNS: '/work-place/returns',
  MISSED_CALLS: '/work-place/missed-calls',
  MY_PROFILE: '/my-profile',
  CATALOG: '/catalog',
  PRODUCT: '/product',
  USER_PROFILE: '/user-profile',
  APPLICATION: '/application',
  SALE: '/sale',
  ADMIN_PANEL: '/admin-panel',
  SIGN_IN: '/sign-in',
  SCANNING: '/scanning',
}
