/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * WT PANEL
 * OpenAPI spec version: 1.0.0
 */
import { createInstance } from './api-instance'
import type { BodyType } from './api-instance'
export type ImagesControllerDeletImageParams = {
  productId: string
  image: string[]
}

export type ImagesControllerUploadImagesBody = {
  files?: Blob[]
  productId?: string
}

export type ProductsControllerGetSimilarProductsParams = {
  q?: string
  addPart?: string
  page: string
  count: string
}

export type ProductsControllerGetProductsParams = {
  q?: string
  addPart?: string
  page: string
  count: string
}

export type PanelControllerGetMissedCallsParams = {
  page: string
  count: string
}

export type PanelControllerGetReturnsParams = {
  page: string
  count: string
}

export type PanelControllerGetCancelsParams = {
  page: string
  count: string
}

export type PanelControllerGetApplicationSaleParams = {
  title: string
  type: string
  page: string
  count: string
  text: string
}

export type TimeControlControllerGetUserWorkTimeParams = {
  userId: string
  startDate: string
  endDate: string
}

export type TimeControlControllerGetAvatarByUserIdParams = {
  userId: string
}

export interface CreateSaleDto {
  bill: string
  date: string
  id: string
  org: string
}

export interface SaleAddTrackNumberReq {
  saleId: string
  trackNumber: string
}

export interface SaleDto {
  article: string
  availability_in_k_warehouse: number
  code: string
  cost: string
  count: string
  id: string
  issued: string
  name: string
  photos: string[]
  place: string
  position: string
  state: string
  sum: string
}

export interface SaleInfo {
  application: Application
  client: number
  date: number
  id: string
  processing: string
  recorded_track_number: boolean
  responsible: string
  status: string
  store_keeper: string
  sub_processing: string
  sum: string
}

export interface SaleResponseDto {
  data: SaleDto[]
  info: SaleInfo
}

export interface ApplicationDto {
  article: string
  availability_in_k_warehouse: number
  code: string
  cost: string
  count: string
  id: string
  issued: string
  name: string
  photos: string[]
  place: string
  position: string
  state: string
  sum: string
}

export interface ApplicationResponseDto {
  data: ApplicationDto[]
  info: ApplicationInfo
}

export interface Application {
  date: number
  id: string
}

export interface ApplicationInfo {
  application: Application
  client: number
  date: number
  id: string
  porter: string
  processing: string
  responsible: string
  status: string
  store_keeper: string
  sub_processing: string
  sum: string
}

export interface ChangeProductInAppSale {
  id: string
  indCode: string
  pose: string
  type: string
}

export interface IssueProductInSaleReq {
  id: string
  pose: string[]
}

export interface ProductDto {
  article: string
  comment: string
  cost: string
  indcode: string
  name: string
  photos: string[]
  sklad: string
}

export interface ProductInfo {
  count: number
  pages: number
}

export interface ProductsResponse {
  data: ProductDto[]
  info: ProductInfo
}

export interface ReqRefusalDto {
  id: string
  reason: string
}

export interface Bill {
  id: string
  name: string
}

export interface BillsInfo {
  count: number
  data: Bill[]
}

export interface OrgsBills {
  bills: BillsInfo
  orgs: OrgsInfo
}

export interface Org {
  id: string
  name: string
}

export interface OrgsInfo {
  count: number
  data: Org[]
}

export interface MoveApplicationSaleDto {
  comment_for_collector: string
  id: string
  move_myself: boolean
  processing: string
  sub_processing: string
  type: string
}

export interface PorterDto {
  id: string
  name: string
  phone: string
}

export interface ResponsibleDto {
  id: string
  name: string
  phone: string
}

export interface DataDto {
  client: string
  flag: number
  id: string
  porter: PorterDto
  processing: string
  responsible: ResponsibleDto
  sub_processing: string
  tk: string
}

export interface InfoDto {
  count: number
  pages: number
}

export interface ApplicationSaleDto {
  data: DataDto[]
  info: InfoDto
}

export interface Category {
  count: number
  title: string
  type: string
}

export interface BadApplication {
  count: string
  state: string
}

export interface WorkTime {
  day: string
  endTime?: string
  startTime?: string
}

export interface WorkTimesInfo {
  absencesCount: number
  lateArrivalsCount: number
  overtimesCount: number
  totalWorkHours: number
  workDaysCount: number
  workTimes: WorkTime[]
}

export interface AvatarDto {
  avatar: string
}

export interface Role {
  id: string
  title: string
}

export interface SessionInfoDto {
  birth_date: string
  company: string
  id: string
  name: string
  personal_phone: string
  post: string
  roles: Role[]
  work_phone: string
}

export interface SignInRequestDto {
  password: string
  phone: string
}

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never

/**
 * @summary Авторизация при помощи 1C
 */
export const authControllerSignInOneC = (
  signInRequestDto: BodyType<SignInRequestDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    {
      url: `/auth/sign-in-one-c`,
      method: 'post',
      headers: { 'Content-Type': 'application/json' },
      data: signInRequestDto,
    },
    options,
  )
}

/**
 * @summary Выход из сессии
 */
export const authControllerSignOut = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>({ url: `/auth/sign-out`, method: 'post' }, options)
}

/**
 * @summary Получение информации о сессии
 */
export const authControllerGetSessionInfo = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<SessionInfoDto>(
    { url: `/auth/session-info`, method: 'get' },
    options,
  )
}

/**
 * @summary Получение фотографии пользователя
 */
export const timeControlControllerGetAvatarByUserId = (
  params: TimeControlControllerGetAvatarByUserIdParams,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<AvatarDto>(
    { url: `/time-control/avatar-by-user-id`, method: 'get', params },
    options,
  )
}

/**
 * @summary Получение информации о рабочем времени
 */
export const timeControlControllerGetUserWorkTime = (
  params: TimeControlControllerGetUserWorkTimeParams,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<WorkTimesInfo>(
    { url: `/time-control/work-time`, method: 'get', params },
    options,
  )
}

/**
 * @summary Получение информации о отказах, возвратах, и пропущенных звонках
 */
export const panelControllerGetBadApplications = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<BadApplication[]>(
    { url: `/panel/bad-applications`, method: 'get' },
    options,
  )
}

/**
 * @summary Получение категорий
 */
export const panelControllerGetCategories = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<Category[]>({ url: `/panel/categories`, method: 'get' }, options)
}

/**
 * @summary Получение заявок и продаж
 */
export const panelControllerGetApplicationSale = (
  params: PanelControllerGetApplicationSaleParams,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<ApplicationSaleDto>(
    { url: `/panel/applications-sales`, method: 'get', params },
    options,
  )
}

/**
 * @summary Перемещение заявок и продаж
 */
export const panelControllerMoveApplicationSale = (
  moveApplicationSaleDto: BodyType<MoveApplicationSaleDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    {
      url: `/panel/move-application-sale`,
      method: 'post',
      headers: { 'Content-Type': 'application/json' },
      data: moveApplicationSaleDto,
    },
    options,
  )
}

/**
 * @summary Получение организация и счетов
 */
export const panelControllerGetOrgsBills = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<OrgsBills>(
    { url: `/panel/organizations-bills`, method: 'get' },
    options,
  )
}

/**
 * @summary Отказы
 */
export const panelControllerGetCancels = (
  params: PanelControllerGetCancelsParams,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<ApplicationSaleDto>(
    { url: `/panel/cancels`, method: 'get', params },
    options,
  )
}

/**
 * @summary Возвраты
 */
export const panelControllerGetReturns = (
  params: PanelControllerGetReturnsParams,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<OrgsBills>(
    { url: `/panel/returns`, method: 'get', params },
    options,
  )
}

/**
 * @summary Пропущенные звонки
 */
export const panelControllerGetMissedCalls = (
  params: PanelControllerGetMissedCallsParams,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<OrgsBills>(
    { url: `/panel/missed-calls`, method: 'get', params },
    options,
  )
}

/**
 * @summary Передать заявку в отказ
 */
export const panelControllerRefusalApplication = (
  reqRefusalDto: BodyType<ReqRefusalDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<OrgsBills>(
    {
      url: `/panel/refusal`,
      method: 'post',
      headers: { 'Content-Type': 'application/json' },
      data: reqRefusalDto,
    },
    options,
  )
}

/**
 * @summary Получение товаров по запросу
 */
export const productsControllerGetProducts = (
  params: ProductsControllerGetProductsParams,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<ProductsResponse>(
    { url: `/products`, method: 'get', params },
    options,
  )
}

/**
 * @summary Получение товара
 */
export const productsControllerGetProduct = (
  id: string,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<ProductDto>(
    { url: `/products/one-product/${id}`, method: 'get' },
    options,
  )
}

/**
 * @summary Получение похожих товаров
 */
export const productsControllerGetSimilarProducts = (
  params: ProductsControllerGetSimilarProductsParams,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<ProductsResponse>(
    { url: `/products/similar-products`, method: 'get', params },
    options,
  )
}

/**
 * @summary Выдача товара в продаже
 */
export const productsControllerIssueProduct = (
  issueProductInSaleReq: BodyType<IssueProductInSaleReq>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    {
      url: `/products/issue-product-in-sale`,
      method: 'post',
      headers: { 'Content-Type': 'application/json' },
      data: issueProductInSaleReq,
    },
    options,
  )
}

/**
 * @summary Изменение товара в заявке или продаже
 */
export const productsControllerChangeProductInAppSale = (
  changeProductInAppSale: BodyType<ChangeProductInAppSale>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    {
      url: `/products/change-product-in-app-sale`,
      method: 'post',
      headers: { 'Content-Type': 'application/json' },
      data: changeProductInAppSale,
    },
    options,
  )
}

/**
 * @summary Получение заявки
 */
export const applicationsControllerGetApplication = (
  id: string,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<ApplicationResponseDto>(
    { url: `/applications/${id}`, method: 'get' },
    options,
  )
}

/**
 * @summary Получение продажи
 */
export const salesControllerGetSale = (
  id: string,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<SaleResponseDto>({ url: `/sales/${id}`, method: 'get' }, options)
}

/**
 * @summary Добавить трек номер к продаже
 */
export const salesControllerAddTrackNumber = (
  saleAddTrackNumberReq: BodyType<SaleAddTrackNumberReq>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    {
      url: `/sales/add-track-number`,
      method: 'post',
      headers: { 'Content-Type': 'application/json' },
      data: saleAddTrackNumberReq,
    },
    options,
  )
}

/**
 * @summary Создание продажи
 */
export const salesControllerCreateSale = (
  createSaleDto: BodyType<CreateSaleDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    {
      url: `/sales/create-sale`,
      method: 'post',
      headers: { 'Content-Type': 'application/json' },
      data: createSaleDto,
    },
    options,
  )
}

export const imagesControllerUploadImages = (
  imagesControllerUploadImagesBody: BodyType<ImagesControllerUploadImagesBody>,
  options?: SecondParameter<typeof createInstance>,
) => {
  const formData = new FormData()
  if (imagesControllerUploadImagesBody.productId !== undefined) {
    formData.append('productId', imagesControllerUploadImagesBody.productId)
  }
  if (imagesControllerUploadImagesBody.files !== undefined) {
    imagesControllerUploadImagesBody.files.forEach((value) =>
      formData.append('files', value),
    )
  }

  return createInstance<void>(
    {
      url: `/images`,
      method: 'post',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    },
    options,
  )
}

export const imagesControllerDeletImage = (
  params: ImagesControllerDeletImageParams,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>({ url: `/images`, method: 'delete', params }, options)
}

export type AuthControllerSignInOneCResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignInOneC>>
>
export type AuthControllerSignOutResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignOut>>
>
export type AuthControllerGetSessionInfoResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetSessionInfo>>
>
export type TimeControlControllerGetAvatarByUserIdResult = NonNullable<
  Awaited<ReturnType<typeof timeControlControllerGetAvatarByUserId>>
>
export type TimeControlControllerGetUserWorkTimeResult = NonNullable<
  Awaited<ReturnType<typeof timeControlControllerGetUserWorkTime>>
>
export type PanelControllerGetBadApplicationsResult = NonNullable<
  Awaited<ReturnType<typeof panelControllerGetBadApplications>>
>
export type PanelControllerGetCategoriesResult = NonNullable<
  Awaited<ReturnType<typeof panelControllerGetCategories>>
>
export type PanelControllerGetApplicationSaleResult = NonNullable<
  Awaited<ReturnType<typeof panelControllerGetApplicationSale>>
>
export type PanelControllerMoveApplicationSaleResult = NonNullable<
  Awaited<ReturnType<typeof panelControllerMoveApplicationSale>>
>
export type PanelControllerGetOrgsBillsResult = NonNullable<
  Awaited<ReturnType<typeof panelControllerGetOrgsBills>>
>
export type PanelControllerGetCancelsResult = NonNullable<
  Awaited<ReturnType<typeof panelControllerGetCancels>>
>
export type PanelControllerGetReturnsResult = NonNullable<
  Awaited<ReturnType<typeof panelControllerGetReturns>>
>
export type PanelControllerGetMissedCallsResult = NonNullable<
  Awaited<ReturnType<typeof panelControllerGetMissedCalls>>
>
export type PanelControllerRefusalApplicationResult = NonNullable<
  Awaited<ReturnType<typeof panelControllerRefusalApplication>>
>
export type ProductsControllerGetProductsResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerGetProducts>>
>
export type ProductsControllerGetProductResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerGetProduct>>
>
export type ProductsControllerGetSimilarProductsResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerGetSimilarProducts>>
>
export type ProductsControllerIssueProductResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerIssueProduct>>
>
export type ProductsControllerChangeProductInAppSaleResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerChangeProductInAppSale>>
>
export type ApplicationsControllerGetApplicationResult = NonNullable<
  Awaited<ReturnType<typeof applicationsControllerGetApplication>>
>
export type SalesControllerGetSaleResult = NonNullable<
  Awaited<ReturnType<typeof salesControllerGetSale>>
>
export type SalesControllerAddTrackNumberResult = NonNullable<
  Awaited<ReturnType<typeof salesControllerAddTrackNumber>>
>
export type SalesControllerCreateSaleResult = NonNullable<
  Awaited<ReturnType<typeof salesControllerCreateSale>>
>
export type ImagesControllerUploadImagesResult = NonNullable<
  Awaited<ReturnType<typeof imagesControllerUploadImages>>
>
export type ImagesControllerDeletImageResult = NonNullable<
  Awaited<ReturnType<typeof imagesControllerDeletImage>>
>
